{
 "title": "Siva Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_classes_loaded, instance)"
   },
   {
    "name": "application",
    "label": "Application",
    "query": "label_values(jvm_classes_loaded{instance=\"$instance\"}, application)"
   }
  ]
 },
 "panels": [
  {
   "title": "5xx",
   "type": "singlestat",
   "description": "Server Error Count",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\", status=~\"5..\"})"
    }
   ]
  },
  {
   "title": "4xx",
   "type": "singlestat",
   "description": "Client Error Count",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\", status=~\"4..\"})"
    }
   ]
  },
  {
   "title": "2xx",
   "type": "singlestat",
   "description": "Success Count",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\", status=~\"2..\"})"
    }
   ]
  },
  {
   "title": "5xx Rate",
   "type": "singlestat",
   "description": "Server Error Count",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\", status=\"500\", uri=~\"/api/.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "API Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\", uri=~\"/api/.*\"}",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  }
 ]
}